adding i/o page
zauberzeug/field_friend pull request #112
Opened 2024-07-09 11:22 UTC by LukasBaecker

Based on the [Testbrain](https://github.com/zauberzeug/test_brain) page, an overview of all i/os of the robot brain is to be created in order to facilitate debugging and detect errors.

TODOs:

- [ ] add new page
- [ ] make all i/os accessible
- [ ] test all i/o
- [ ] ...on a real system

2024-07-10 17:20 UTC, rodja commented on field_friend/interface/pages/io_page.py
> +                        status_bulb(False)
@LukasBaecker tis can be written much tighter:
```py
status_bulb(self.system.field_friend.estop.is_soft_estop_active)
```

2024-07-24 15:01 UTC, LukasBaecker commented
I optimised the I/O page and moved it to the dev page which now contains only the dev tools and the i/o overview. 
Furthermore, I tested the i/o overview with the U4.

2024-07-24 18:27 UTC, pascalzauberzeug requested changes

2024-07-24 18:27 UTC, pascalzauberzeug commented on field_friend/interface/components/status_bulb.py
> +            if status else self.style("height: 15px; width: 15px; margin: auto; background: radial-gradient(circle at 5px 5px, #2E5396, #294790); border-radius: 50%;")
pylint doesn't like the inline if, how about: 
```suggestion
        self.style("height: 15px; width: 15px; margin: auto; border-radius: 50%")
        self.style(add="background: radial-gradient(circle at 5px 5px, #5FE5E0, #5898D4); box-shadow: #5FE5E066 0px 0px 10px 5px;" if status else "background: radial-gradient(circle at 5px 5px, #2E5396, #294790);")
```

2024-07-24 18:27 UTC, pascalzauberzeug commented on field_friend/interface/components/io_sockets.py
I'm not sure about the with-as names.
On the one hand I really like them because they provide explanation for the code block, on the other hand they are not used and pylance complains.
If we keep them, we should add a pylance ignore for them

2024-07-24 18:37 UTC, pascalzauberzeug commented on field_friend/interface/components/io_sockets.py
> +                                                            lambda active_bumpers: not (True if 'back' in active_bumpers else False))
```suggestion
                    status_bulb(True).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                           lambda active_bumpers: 'front_top' in active_bumpers)
                    status_bulb(False).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                            lambda active_bumpers: 'front_top' not in active_bumpers)
                    ui.label('Front Top Bumper')
                with ui.row():
                    status_bulb(True).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                           lambda active_bumpers: 'front_bottom' in active_bumpers)
                    status_bulb(False).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                            lambda active_bumpers: 'front_bottom' not in active_bumpers)
                    ui.label('Front Bottom Bumper')
                with ui.row():
                    status_bulb(True).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                           lambda active_bumpers: 'back' in active_bumpers)
                    status_bulb(False).bind_visibility_from(self.system.field_friend.bumper, 'active_bumpers',
                                                            lambda active_bumpers: 'back' not in active_bumpers)
```

2024-07-24 18:38 UTC, pascalzauberzeug commented on field_friend/interface/components/io_sockets.py
How about a function to turn a status_bulb on and off, instead of having two bulbs at the same time?

2024-07-25 13:07 UTC, LukasBaecker commented on field_friend/interface/components/io_sockets.py
I deleted them, I think the structure should be similarly clear without the naming

2024-07-25 13:18 UTC, LukasBaecker commented on field_friend/interface/components/status_bulb.py
> +            if status else self.style("height: 15px; width: 15px; margin: auto; background: radial-gradient(circle at 5px 5px, #2E5396, #294790); border-radius: 50%;")
nice change, thank you

2024-07-25 14:09 UTC, LukasBaecker commented on field_friend/interface/components/io_sockets.py
I changed the status_bulb to a ValueElement, so that I can bind a value to it and manipulate the style inside the bulb instead of changing the visibility between two bulb as you can see here

2024-07-25 16:22 UTC, pascalzauberzeug approved these changes
I fixed the shadow that remained after turning the bulb off in https://github.com/zauberzeug/field_friend/pull/112/commits/bf9e0e603bbf3abe53c98bc6b839496949347538 and took the liberty to also use the wheels card in simulation, since the connected-bulb wasn't working correctly. https://github.com/zauberzeug/field_friend/pull/112/commits/96fa3588bbeb66350addf3abe03a01c0134a415f

What was the mutex path for? https://github.com/zauberzeug/field_friend/pull/112/commits/ab0541a3ea8fb337cb331d6bfcba5319f0d02198

2024-07-26 06:29 UTC, merged