D1 axis
zauberzeug/field_friend pull request #159
Opened 2024-08-27 06:19 UTC by Johannes-Thiel

This is a integration of the D1 motorcontroller axis in the Fieldfriend repository.
In this pull request the baseclasses YAxis and ZAxis are combined into the Axis base class.

2024-08-27 07:01 UTC, Johannes-Thiel commented
tested with f13(tornado) and rb19(D1 testbench), in simulation with u4(tornado),u5(wheet screw),rb19(D1),u3(chain axis)

2024-09-03 13:16 UTC, LukasBaecker requested changes
Reviewed and changes where immediately worked out.

2024-09-03 13:19 UTC, Johannes-Thiel commented
Blocked until https://github.com/zauberzeug/lizard/pull/63 is reviewed and merged.

2024-09-04 11:18 UTC, LukasBaecker approved these changes

2024-09-04 11:19 UTC, merged