Improved GNSS pausing
zauberzeug/field_friend pull request #177
Opened 2024-09-06 12:34 UTC by SeaTechRC

Hello,

This PR contains an improved method for pausing the GNSS during fine adjusting of the robot when approaching a crop.
Instead of relying on an external task to constantly check if the GNSS is unpaused, the GNSS is paused by use of a contextmanager, which is more clear and is safer in case of unexpected failures.

There is also an improvement on how GNSS data is handled: The amount of points to average over is set and stale data gets discarded ensuring, that we don't accidentally average over data from a long drive.

There might be some considerations for when exactly to pause the GNSS, but as of this PR, all fine adjustment with the GNSS paused happens in the puncher class.

2024-09-06 15:10 UTC, pascalzauberzeug commented
Nice idea, we will probably test it on tuesday

2024-09-07 04:11 UTC, rodja requested changes
Thanks for the PR, @SeaTechRC. Much appreciated. Just from looking at it, I can imagine it to be a great improvement.

Beside my comments I stumbled upon your remark in the description:

> all fine adjustment with the GNSS paused happens in the puncher class

Could you elaborate on this? There seem to be no modifications in the puncher class.

2024-09-07 04:11 UTC, rodja commented on field_friend/automations/navigation/navigation.py
>                      continue
The `continue` is obsolete because of the newly introduced `else`.
```suggestion
```

2024-09-07 04:11 UTC, rodja commented on field_friend/automations/navigation/navigation.py
> -            await self.gnss.update_robot_pose()
by removing the update before starting the automation, the gnss localization might not be accurately performed at the beginning. Or am I mistaken?

2024-09-07 04:11 UTC, rodja commented on field_friend/localization/gnss.py
> -            'min_seconds_between_updates': self.min_seconds_between_updates,
Ah yes. This was a relict of an experiment before. If this is cleaned up, the member variable and the contstant should be removed too.

2024-09-09 15:41 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +    def pause(self):
You are right, `paused` is correct in this case.
Another naming tense is `-ing`, more info [here](https://peps.python.org/pep-0343/#examples)

2024-09-09 15:58 UTC, pascalzauberzeug commented on field_friend/automations/navigation/navigation.py
> +                    with self.gnss.pause(): # Pause GNSS for better local accuracy
@SeaTechRC @rodja isn't this the wrong way around? We want to pause while we drive and get position updates during the workflow.

2024-09-09 15:59 UTC, pascalzauberzeug commented on field_friend/automations/navigation/navigation.py
> -            await self.gnss.update_robot_pose()
I think you are correct, this led me to this idea: https://github.com/zauberzeug/field_friend/pull/177/files#r1750526972

2024-09-10 08:44 UTC, SeaTechRC commented
> Thanks for the PR, @SeaTechRC. Much appreciated. Just from looking at it, I can imagine it to be a great improvement.
> 
> Beside my comments I stumbled upon your remark in the description:
> 
> > all fine adjustment with the GNSS paused happens in the puncher class
> 
> Could you elaborate on this? There seem to be no modifications in the puncher class.

Sorry, seems to be a misunderstanding on my end.
I was under the impression, the drive_and_punch method was being used. However, this is not the case. Therefore, the GNSS needs to be paused for the final approach, when the distance is lower that MAX_STRETCH_DISTANCE (meaning a plant is in sight).

2024-09-10 10:28 UTC, SeaTechRC commented
The change to [field_friend/hardware/status_control.py](https://github.com/zauberzeug/field_friend/pull/177/files/623719bb17a95af64cdd706539787ed00cc54e86#diff-3bd964783bb3a03efcf2c018426d3c51820f05febaadcefa15b879bd70f629de) is caused by trouble with the autocrlf feature of git on windows. The file actually has the CR LF line endings instead of LF line endings.

In order to remove this change, I would have to rebase and force push, which would remove the review comments.
I would address the other issues aswell and then force push of that is acceptable.

2024-09-10 13:30 UTC, SeaTechRC commented on field_friend/automations/navigation/navigation.py
> +                    with self.gnss.pause(): # Pause GNSS for better local accuracy
Indeed. The final approach to a plant should be handled without GNSS input.
Fixed in 3d99d1b8807eaec476fe3fdaa0fea9fefca8180d

2024-09-10 13:49 UTC, SeaTechRC commented
Thankfully it seems that force pushing no longer removes review comments. 🎉

2024-09-10 13:52 UTC, SeaTechRC commented on field_friend/automations/navigation/navigation.py
> -            await self.gnss.update_robot_pose()
[254df8e](https://github.com/zauberzeug/field_friend/pull/177/commits/254df8e26042f75be2a47a976c093cc7f45852c3) and [1ca960a](https://github.com/zauberzeug/field_friend/pull/177/commits/1ca960afa40d60d6bb64d10e7ad2299e94e8c007) reverts it to the same behaviour before the change.

2024-09-10 13:53 UTC, SeaTechRC commented on field_friend/localization/gnss.py
> +    def pause(self):
Changed in [16c7048](https://github.com/zauberzeug/field_friend/pull/177/commits/16c7048a66cac90d11eac04ffa633b4b0aadc2b5)

2024-09-10 23:39 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +    async def wait_for_updated_robot_pose(self) -> None:
I would prefer to use `ROBOT_POSE_LOCATED` since  `_update_robot_pose` already emits it, but rosys events sadly don't have a wait function.

The only thing coming to my mind is something like this, which isn't really pretty either
```python
import rosys
from nicegui import ui

ROBOT_POSE_LOCATED = rosys.event.Event()

ui.button('Click me!', on_click=ROBOT_POSE_LOCATED.emit)


async def wait_for_updated_robot_pose():
    waiting = True

    def on_robot_pose_located():
        nonlocal waiting
        print('Robot pose located!')
        waiting = False

    ROBOT_POSE_LOCATED.register(on_robot_pose_located)
    while waiting:
        await rosys.sleep(0.1)
        print('Continuing...')
    print('Done!')

rosys.on_startup(wait_for_updated_robot_pose)
ui.run()
```

2024-09-10 23:41 UTC, pascalzauberzeug commented on field_friend/hardware/status_control.py
fixed by https://github.com/zauberzeug/field_friend/pull/177#issuecomment-2340280069

2024-09-11 03:07 UTC, rodja commented on field_friend/hardware/safety.py
Is this change related to GNSS? Otherwise it should be in a separate pull request.

2024-09-11 07:49 UTC, SeaTechRC commented on field_friend/hardware/safety.py
It's from the merge of cbd60aa266ae1bf87de73a11236c289ff5baa46d
I sync'd the main branch to my fork for testing purposes.

2024-09-11 08:30 UTC, SeaTechRC commented on field_friend/localization/gnss.py
> +    async def wait_for_updated_robot_pose(self) -> None:
A cleaner solution without a second event as attribute:
``import asyncio
import rosys
from nicegui import ui

ROBOT_POSE_LOCATED = rosys.event.Event()

ui.button('Click me!', on_click=ROBOT_POSE_LOCATED.emit)


async def wait_for_updated_robot_pose() -> None:
    event = asyncio.Event()
    def callback():
        nonlocal event
        event.set()
        ROBOT_POSE_LOCATED.unregister(callback)
        print("Unregistered")
    
    ROBOT_POSE_LOCATED.register(callback)
    print("Waiting...")
    await event.wait()
    print("Fired!")


rosys.on_startup(wait_for_updated_robot_pose)
ui.run()``

2024-09-11 13:10 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +    async def wait_for_updated_robot_pose(self) -> None:
Nice! I think we can use this one and I will definitely bring waiting for rosys events on the table

2024-09-12 08:43 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +    async def wait_for_updated_robot_pose(self) -> None:
@SeaTechRC we just talked about this internally, I will implement this wait-function in rosys, but until then you can implement it here

2024-09-13 08:15 UTC, SeaTechRC commented
Quick notice: On the main branch, the attribute is_paused of the GNSS is used in the status_dev interface component.
An extra commit after the merge is needed.

2024-09-13 09:40 UTC, pascalzauberzeug commented
@SeaTechRC you could just add a property to gnss
```python
@property
def is_paused(self) -> bool:
    return self._is_paused
```

2024-09-13 10:19 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
>          assert not self._is_paused
I think this `assert` should be removed. You can't wait for an update like this, when it is paused

2024-09-13 10:24 UTC, SeaTechRC commented on field_friend/localization/gnss.py
>          assert not self._is_paused
That's the intention. In case the GNSS is paused, this would raise an AssertionError.
There is the risk to wait forever on the event.
Perhaps an optional timeout parameter would be more adequate.

2024-09-13 12:05 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
>          assert not self._is_paused
Okay, claude.ai suggests this:
```python
async def wait_for_updated_robot_pose(self, timeout: float = 10.0) -> None:
    event = asyncio.Event()
    
    def callback():
        nonlocal event
        event.set()
        self.ROBOT_POSE_LOCATED.unregister(callback)
    
    try:
        self.ROBOT_POSE_LOCATED.register(callback)
        await asyncio.wait_for(event.wait(), timeout=timeout)
    except asyncio.TimeoutError:
        self.ROBOT_POSE_LOCATED.unregister(callback)
        raise TimeoutError(f"Timed out waiting for robot pose update after {timeout} seconds")
```

2024-09-13 12:36 UTC, SeaTechRC commented on field_friend/localization/gnss.py
>          assert not self._is_paused
Took it as inspiration, there were two details I touched up.
 - Timeout can be None (as without an explicit timeout, perhaps you want to wait forever?)
 - Cleaner handling of the TimeoutError

2024-09-13 13:54 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +        self._pose_update.clear()
```suggestion
```
This is no longer needed

2024-09-13 13:56 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
> +    async def wait_for_robot_pose_update(self, timeout: Optional[float] = None) -> None:
```suggestion
    async def wait_for_robot_pose_update(self, timeout: float | None = None) -> None:
```
The [styling guide](https://discuss.python.org/t/clarification-for-pep-604-is-foo-int-none-to-replace-all-use-of-foo-optional-int/26945) calls for `| None` instead of `Optional` for Python 3.10+ and we want to gradually follow that

2024-09-13 13:57 UTC, pascalzauberzeug commented on field_friend/localization/gnss.py
>          self.current: Optional[GNSSRecord] = None
```suggestion
        self.current: GNSSRecord | None = None
```
Same as below

2024-09-19 07:58 UTC, rodja commented
I just discovered that we will get positioning errors if the robot is driven manually. Before this PR, position updates where triggered explicitly. With the changes here position updates are allowed all the time but are paused in specific circumstances.

Maybe in `gnss.py` we can check the odometer if the robot has moved and else do not call `_update_robot_pose` at all. This may also lead to not needing a pause functionality at all...

2024-10-14 09:29 UTC, pascalzauberzeug commented
@SeaTechRC Based on this discussion I removed the need to pause to get gnss updates; https://github.com/zauberzeug/field_friend/pull/189
I also brought our event waiting idea to rosys https://github.com/zauberzeug/rosys/pull/210

2024-10-22 13:29 UTC, pascalzauberzeug commented
We merged https://github.com/zauberzeug/field_friend/pull/189, I will close this one now

2024-10-22 13:29 UTC, closed without merging