Field Creation Wizard and Field Class Changes
zauberzeug/field_friend pull request #183
Opened 2024-09-20 09:58 UTC by LukasBaecker

In the course of planning the new field navigation #180 , the wizard for creating fields will be updated and will be accessible from the start page (the field_planner will be deactivated temporary). In addition, fields will be saved differently from now on. Only the AB line and a few field parameters will be saved persistently. Rows and the perimeter of the field will from now on be calculated dynamically from the parameters. For now we concentrate on only one field for one robot. Also, obstacles will be added in future and are neglected. 

Todos:

- [ ]  update Field Creation Wizard and move it to the main page
- [ ] update Field class (save needed params and calculate rows and boundary)
- [ ] deactivate field_planner
- [ ] visualize the field in leaflet
- [ ] update tests

2024-09-27 17:53 UTC, pascalzauberzeug commented on field_friend/automations/field_parameters.py
> +class FieldParameters():
The parentheses are only needed when the class extends another
```suggestion
class FieldParameters:
```

2024-09-27 18:00 UTC, pascalzauberzeug commented on field_friend/automations/field_parameters.py
> +    def field(self) -> 'Field':
```suggestion
    def field(self) -> Field:
```

2024-09-27 18:01 UTC, pascalzauberzeug commented on field_friend/automations/field_parameters.py
> +from dataclasses import dataclass
```suggestion
```

2024-10-01 05:23 UTC, rodja requested changes
I just had a short glance at the PR, but want to share some thoughts:
- code which we not use anymore should be removed not left in a comment (we have git to not loose code)
- I find it quite hard to differentiate between `Field` and `FieldParameters`; I think the code would get much simpler if we simply had a `Field` with `first_row_start`, first_row_end`, `row_spacing`, and `row_count` which are persistent. Whenever they change we would call an internal method `_refresh` which updates the non-persistent properties `rows` and `points`.
- There are still some leftovers like `obstacle` property in Field which we do not need (yet).

2024-10-02 07:38 UTC, LukasBaecker commented
> I just had a short glance at the PR, but want to share some thoughts:
> 
> * code which we not use anymore should be removed not left in a comment (we have git to not loose code)
> * I find it quite hard to differentiate between `Field` and `FieldParameters`; I think the code would get much simpler if we simply had a `Field` with `first_row_start`, first_row_end`, `row_spacing`, and `row_count`which are persistent. Whenever they change we would call an internal method`_refresh`which updates the non-persistent properties`rows`and`points`.
> * There are still some leftovers like `obstacle` property in Field which we do not need (yet).

I have made changes according to your feedback.

Now there seems to be an error when creating a field. The first field is created correctly, but the following ones have errors in the calculation of the rows and the perimeter, which I need to solve.

2024-10-02 14:56 UTC, LukasBaecker commented
> > I just had a short glance at the PR, but want to share some thoughts:
> > 
> > * code which we not use anymore should be removed not left in a comment (we have git to not loose code)
> > * I find it quite hard to differentiate between `Field` and `FieldParameters`; I think the code would get much simpler if we simply had a `Field` with `first_row_start`, first_row_end`, `row_spacing`, and `row_count`which are persistent. Whenever they change we would call an internal method`_refresh`which updates the non-persistent properties`rows`and`points`.
> > * There are still some leftovers like `obstacle` property in Field which we do not need (yet).
> 
> I have made changes according to your feedback.
> 
> Now there seems to be an error when creating a field. The first field is created correctly, but the following ones have errors in the calculation of the rows and the perimeter, which I need to solve.

Fixed.

2024-10-14 09:40 UTC, pascalzauberzeug commented on field_friend/automations/field_provider.py
> +        for field in list(fields_data.values()):
```
2024-10-14 11:37:24.309 [ERROR] rosys/persistence/registry.py:62: failed to restore <field_friend.automations.field_provider.FieldProvider object at 0x130838260>
Traceback (most recent call last):
  File "/Users/pascal/Develop/field_friend/field_friend/.venv/lib/python3.12/site-packages/rosys/persistence/registry.py", line 60, in restore
    module.restore(json.loads(filepath.read_text()))
  File "/Users/pascal/Develop/field_friend/field_friend/field_friend/automations/field_provider.py", line 29, in restore
    for field in list(fields_data.values()):
                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'values'
```
fields_data is a list, not a dictionary

2024-10-14 09:44 UTC, pascalzauberzeug commented on field_friend/automations/field_provider.py
> +        self.needs_backup: bool = False
```suggestion
```
I think this line can go, because it's already in rosys https://github.com/zauberzeug/rosys/blob/ac22057fbdb4db9cde4c6ef917131af7d4e05a06/rosys/persistence/persistent_module.py#L12

2024-10-14 09:51 UTC, pascalzauberzeug commented on tests/test_field_provider.py
> +        assert r.points[1].long == pytest.approx(field.first_row_end.shifted(Point(x=0, y=-shift)).long, 0.000000001)
```suggestion
        assert r.points[0].lat == pytest.approx(field.first_row_start.lat, 0.000_000_001)
        assert r.points[0].long == pytest.approx(field.first_row_start.shifted(Point(x=0, y=-shift)).long, 0.000_000_001)
        assert r.points[1].lat == pytest.approx(field.first_row_end.lat, 0.000_000_001)
        assert r.points[1].long == pytest.approx(field.first_row_end.shifted(Point(x=0, y=-shift)).long, 0.000_000_001)
```
for better readability

2024-10-14 09:55 UTC, pascalzauberzeug commented on tests/test_field_creator.py
> +    assert len(system.field_provider.fields[0].rows) == 10
I think this test is misleading, because you are not testing any geometry computation. It's only checked whether the parameters are set correctly

2024-10-14 09:56 UTC, pascalzauberzeug commented on tests/test_field_creator.py
> +    assert len(system.field_provider.fields[0].rows) == 10, 'the row should still be there even if the spacing is wrong'
I think setting a row spacing of 0 should not even be possible

2024-10-14 11:48 UTC, LukasBaecker commented on tests/test_field_creator.py
> +    assert len(system.field_provider.fields[0].rows) == 10, 'the row should still be there even if the spacing is wrong'
minimum value of row spacing is 1 in the field_creator -> minimum 1cm

2024-10-14 11:56 UTC, pascalzauberzeug commented on field_friend/automations/field_provider.py
> +        for field in list(fields_data.values()):
This is caused by an old persistence. Can be fixed by deleting the field_provider persistence, but this will also delete all previously created fields (which are no longer supported anyway).

2024-10-14 13:54 UTC, pascalzauberzeug approved these changes
Tested on F13, approved!

2024-10-14 13:55 UTC, merged