add Automation time tracking
zauberzeug/field_friend pull request #190
Opened 2024-10-07 14:14 UTC by Johannes-Thiel

There is a Timetracker. But it seams to be used for Time on a specific field.
I made a tracker to track all the time in automations. This Tacker works for all weeding implements and the Recorder. It can be seen in the status drawer.
![image](https://github.com/user-attachments/assets/36a78432-c3bf-4302-849b-37d2e74104d6)

2024-10-07 14:16 UTC, Johannes-Thiel commented
At the moment the time is in seconds, we should talk about the correct format of the data.

2024-10-09 08:54 UTC, Johannes-Thiel commented
The tracking was moved to the base implement. The unnecessary Kpis were removed and are no longer shown in the UI.
The working Hours can be seen in the Status drawer on the right side of the UI.

2024-10-13 20:39 UTC, pascalzauberzeug requested changes
I think we should talk about what we really want to track. Going by these changes the time when changing rows won't be tracked because the implements are deactivated during that.

2024-10-13 20:39 UTC, pascalzauberzeug commented on field_friend/automations/implements/implement.py
> +            self.start_time = rosys.time()
```suggestion
            self.start_time = rosys.time()
```
What happened here? 😄

2024-10-15 06:20 UTC, Johannes-Thiel commented on field_friend/automations/implements/implement.py
> +            self.start_time = rosys.time()
I Have no idea 😄

2024-10-15 06:21 UTC, Johannes-Thiel commented on field_friend/automations/implements/implement.py
> +            self.start_time = rosys.time()
i dont know.

2024-10-15 07:02 UTC, Johannes-Thiel commented
maybe we could put this tracking into the navigation?

2024-10-16 07:42 UTC, LukasBaecker requested changes

2024-10-16 09:51 UTC, LukasBaecker approved these changes

2024-10-16 11:07 UTC, merged