adding fields options and delete button, make fields deletable
zauberzeug/field_friend pull request #209
Opened 2024-10-22 13:01 UTC by LukasBaecker

Currently only a single field can be saved to the field_provider. This PR implements the ability to save, handle and delete multiple fields. Also some improvements for the UI in managing the fields will be added

2024-10-24 08:55 UTC, pascalzauberzeug commented on field_friend/interface/components/leaflet_map.py
> +        self.field_provider.FIELD_SELECTED.register(self.update_layers)
```suggestion
        self.field_provider.FIELDS_CHANGED.register_ui(self.update_layers)
        self.field_provider.FIELD_SELECTED.register_ui(self.update_layers)
```
Do we need `register_ui` here as well?

2024-10-25 00:01 UTC, pascalzauberzeug requested changes

2024-10-25 05:58 UTC, LukasBaecker commented on field_friend/interface/components/leaflet_map.py
> +            self.field_layers.append(self.m.generic_layer(name='polygon',
Yes, I thought of seeing them all on the map is a good overview and then highlighting the selected field would give the user more detailed information (showing rows only of the selected one).

2024-10-25 11:31 UTC, LukasBaecker commented on field_friend/automations/navigation/field_navigation.py
I now save the selected_field in persistence. In the field_navgiation only the id of the field will be updated when another field is selected. When starting the navigation the field will be saved for the navigation independently to prevent a selection of crashing the navigation automation.

2024-10-25 13:27 UTC, pascalzauberzeug requested changes
**TODO:**
- [x] When I create a field, the row spacing is in cm, but when I edit it, it's meter. That needs to be fixed
- [ ] The 3D scene doesn't load the new field anymore when it is selected

2024-10-25 14:11 UTC, pascalzauberzeug approved these changes

2024-10-25 14:11 UTC, merged